package com.system.po;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.userID
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.userName
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthYear
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private Date birthyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private Date grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.collegeID
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private Integer collegeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.role
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    private Byte role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.userID
     *
     * @return the value of student.userID
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.userID
     *
     * @param userid the value for student.userID
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.userName
     *
     * @return the value of student.userName
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.userName
     *
     * @param username the value for student.userName
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthYear
     *
     * @return the value of student.birthYear
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public Date getBirthyear() {
        return birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthYear
     *
     * @param birthyear the value for student.birthYear
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setBirthyear(Date birthyear) {
        this.birthyear = birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public Date getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setGrade(Date grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.collegeID
     *
     * @return the value of student.collegeID
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.collegeID
     *
     * @param collegeid the value for student.collegeID
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.role
     *
     * @return the value of student.role
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public Byte getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.role
     *
     * @param role the value for student.role
     *
     * @mbggenerated Fri Feb 16 21:39:10 CST 2018
     */
    public void setRole(Byte role) {
        this.role = role;
    }
}