package com.system.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.system.po.SelectedCourseCustom;
import com.system.po.Selectedcourse;
import com.system.po.SelectedcourseExample;
import com.system.po.StudentGrade;

public interface SelectedcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    int countByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    int deleteByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    int insert(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    int insertSelective(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    List<Selectedcourse> selectByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbggenerated Thu Feb 22 18:42:25 CST 2018
     */
    int updateByExample(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);


    /*******************************************************/
    
    List<SelectedCourseCustom> getSelectedCourseList(@Param("id")String id);
    
    List<SelectedCourseCustom> getOverCourseList(@Param("id")String id);
    
    List<Selectedcourse> getStudentSelectedCourseid(@Param("id")String id);
    
    List<StudentGrade> getStudentGradeByCourseId(@Param("id")int id);
}